### ISSUE TITLE
Shorthands are not rendered right when making subscripts

### ISSUE THREAD

**Issue by HyperbolicSpaceman** [EpicEricEE/typst-quick-maths#2]
I defined a shorthand:
```
#show: shorthands.with(
    ($@*$, $times.circle$),
  )
```
but when I type `$@*_C$`, it is rendered as 
<img width="45" alt="Screenshot 2024-09-12 at 00 56 56" src="https://github.com/user-attachments/assets/ed3c798e-48c0-4ddd-85b1-c65a5a7febe9">
instead of 
<img width="33" alt="Screenshot 2024-09-12 at 00 57 12" src="https://github.com/user-attachments/assets/6360abca-c2c8-443f-bfff-62a41276b725">

**Comment by acsor** [comment]
As an user of this package, I endorse this issue. Correctly managing subscripts is more than an edge case. Suppose in fact you have a content block where a certain command in an equation is repeated very often, and you want to replace that command with a shorter expression that applies only locally. Recently, I had to develop this definition where the `underline` command is repeated very often:

```typst
#definition(name: [Herbrand model])[
    Given an ASP program $Pi$, an interpretation $I subset.eq "HB"(Pi)$ is a _Herbrand model_ of 

    - A ground rule $r = H (underline(t)_0) <- P_1 (underline(t)_1), ..., P_n (underline(t)_n).$ of $Pi$ if $ { P_1 (underline(t)_1), ..., P_n (underline(t)_n) } subset.eq I$ implies $H (underline(t)_0) in I$;
    - A rule $r = H (underline(x)_0) <- P_1 (underline(x)_1), ..., P_n (underline(x)_n).$ if $I$ is a Herbrand model of all ground instances of $r$;
    - $Pi$ if $I$ is a Herbrand model of all rules of $Pi$.
]
```

I tried doing something like the following using `shorthands`, but I couldn't get it working.

```typst
#definition(name: [Herbrand model])[
    #show: shorthands.with(
	($t$, $underline("t")$),
	($x$, $underline("x")$)
    )
    Given an ASP program $Pi$, an interpretation $I subset.eq "HB"(Pi)$ is a _Herbrand model_ of 

    - A ground rule $r = H (t_0) <- P_1 (t_1), ..., P_n (t_n).$ of $Pi$ if $ { P_1 (t_1), ..., P_n (t_n) } subset.eq I$ implies $H (t_0) in I$;
    - A rule $r = H (x_0) <- P_1 (x_1), ..., P_n (x_n).$ if $I$ is a Herbrand model of all ground instances of $r$;
    - $Pi$ if $I$ is a Herbrand model of all rules of $Pi$.
]
```

It goes without saying that correctly handling subscripts in this package would increase its usefulness.

**Comment by EpicEricEE** [comment]
The problem is that the attachment happens before the shorthand is converted, thus when this package tries to apply the shorthands, it sees the content sequence `([@], attach([*], b: [C]))`, which it currently cannot convert as it doesn't match the given shorthand `([@], [*])`. Parsing and replacing this correctly for all math elements is probably going to be a bit of work.

In @acsor's case, you can probably get around it by just using normal show rules, as it doesn't involve multi-character shorthands, which can't currently be matched with regexes:
```typ
#definition(...)[
  #show math.equation: it => {
    show regex("^(t|x)$"): math.underline // or maybe regex("\b(t|x)\b")
    it
  }

  Given ...
]
```

**Comment by EpicEricEE** [comment]
I have added better support for single-element shorthands, and an exception for attachments and fractions, so that you can do things like

```typ
#show: shorthands.with(($@*$, $times.circle$))

$ x @*_C y \
  x / @* $
```

This is still limiting _(and cursed)_, as you can't have shorthands in attachments like that, but that just doesn't seem possible. Consider the case
```typ
#show: shorthands.with($+-$, $plus.minus$)

$ A_+^+- $
```
which would be detected as the sequence `(attach([A], t: [+], b: [+]), [-])`. As this representation internally has a fixed argument order, the same sequence would result from `$ A^+_+- $`, so it would be impossible tell whether the top or bottom attachment should be converted to `±`.
